[package]
name = "kadai3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
clap = "2.33.3"
image = "0.23.14"
fft2d = { version = "0.1.0", features = [ "rustdct" ] }
